import {
  Bell,
  Camera,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleUserRound,
  GalleryHorizontalEnd,
  Grid2x2,
  Image,
  LogOut,
  Palette,
  RefreshCcw,
  Search,
  UserRound,
  Zap,
} from "@tamagui/lucide-icons";

export const Icons = {
  bell: Bell,
  camera: Camera,
  check: Check,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  circleUserRound: CircleUserRound,
  galleryHorizontalEnd: GalleryHorizontalEnd,
  grid2x2: Grid2x2,
  image: Image,
  logout: LogOut,
  palette: Palette,
  refreshCcw: RefreshCcw,
  search: Search,
  userRound: UserRound,
  zap: Zap,
};
