import {
  ArrowDownWideNarrow,
  ArrowUpWideNarrow,
  Bell,
  Camera,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleUserRound,
  Clock,
  Ellipsis,
  GalleryHorizontalEnd,
  Grid2x2,
  Heart,
  Image,
  Languages,
  LogOut,
  Palette,
  RefreshCcw,
  RotateCcw,
  Search,
  Shirt,
  ShoppingCart,
  SlidersHorizontal,
  ThumbsDown,
  ThumbsUp,
  UserRound,
  X,
  Zap,
} from "@tamagui/lucide-icons";

export const Icons = {
  arrowDownWideNarrow: ArrowDownWideNarrow,
  arrowUpWideNarrow: ArrowUpWideNarrow,
  bell: Bell,
  camera: Camera,
  check: Check,
  checkCircle: CheckCircle,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  circleUserRound: CircleUserRound,
  clock: Clock,
  ellipsis: Ellipsis,
  galleryHorizontalEnd: GalleryHorizontalEnd,
  grid2x2: Grid2x2,
  heart: Heart,
  image: Image,
  languages: Languages,
  logout: LogOut,
  palette: Palette,
  refreshCcw: RefreshCcw,
  rotateCcw: RotateCcw,
  search: Search,
  shirt: Shirt,
  shoppingCart: ShoppingCart,
  slidersHorizontal: SlidersHorizontal,
  thumbsDown: ThumbsDown,
  thumbsUp: ThumbsUp,
  userRound: UserRound,
  x: X,
  zap: Zap,
};
